### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by zkrige** [iteufel/nwjs-ffmpeg-prebuilt#105]
It appears this project has been abandoned or perhaps @iteufel is no longer able to maintain it. Has anyone forked it in order to continue producing binaries for latest nwjs?

**Comment by iteufel** [comment]
I have a lot of work to do lately, but if there is someone who would help it would be good 😌.

@zkrige I'll try to build new libraries right away.

**Comment by zkrige** [comment]
I'd be happy to help - Can you advise what needs to be done?

**Comment by zkrige** [comment]
@iteufel I'm happy to help you with doing builds - I know people get busy and you dont always have time. perhaps I can help lighten your load

**Comment by iteufel** [comment]
@zkrige Building the windows libraries took a little longer because I had to update my build VM.

It would be good if we can automate the builds with the github actions. I tried it before but didn't have the time to do it.
The linux build already works we need to figure out why mac and window don't build.

**Comment by zkrige** [comment]
As an outsider I dont have access to the repo build actions - would it be possible to share them?

**Comment by agran** [comment]
> The linux build already works we need to figure out why mac and window don't build.

Yesterday I compiled the dll for Windows on my PC, so I figured it out a bit. I'll try to work on the question.

**Comment by zkrige** [comment]
@agran fyi: #107
